version: '3'

services:

  ctchan-server:
    build: ./containers/nginx
    container_name: ctchan-server
    volumes:
      - ./containers/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend
    ports:
      - 80:80

  ctchan-app:
    build:
      context: ./containers/app
      dockerfile: Dockerfile.dev
    container_name: ctchan-app
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./containers/app/src:/app/src
      - ./containers/app/public:/app/public
    networks:
      - frontend
    expose:
      - 3000

  ctchan-api:
    build:
      context: ./containers/api
      dockerfile: Dockerfile.dev
    container_name: ctchan-api
    environment:
      FLASK_ENV: 'development'
    volumes:
      - ./containers/api/src:/srv/src
    networks:
      - backend
    expose:
      - 8080

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
