version: '3'

services:

  server:
    build: 
      context: './containers/nginx'
      dockerfile: 'Dockerfile.dev'
    container_name: 'server'
    volumes:
      - './containers/nginx/nginx.dev.conf:/etc/nginx/nginx.conf'
    networks:
      - 'frontend'
      - 'backend'
    ports:
      - '80:80'

  app:
    build: 
      context: './containers/app'
      dockerfile: 'Dockerfile.dev'
    container_name: 'app'
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - './containers/app/src:/app/src'
      - './containers/app/public:/app/public'
    networks:
      - 'frontend'
    expose:
      - '3000'

  api:
    build: './containers/api'
    container_name: 'api'
    environment:
      FLASK_ENV: 'development'
    volumes:
      - './containers/api/src:/srv/src'
    networks:
      - 'backend'
    expose:
      - '8080'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
