version: '3'

services:

  ctchan-server:
    build: ./containers/nginx
    container_name: ctchan-server
    volumes:
      - ./containers/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 3030:3030

  ctchan-app:
    build:
      context: ./containers/app
      dockerfile: Dockerfile.dev
    container_name: ctchan-app
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./containers/app/src:/app/src
      - ./containers/app/public:/app/public
    networks:
      - frontend
    expose:
      - 3000

  thedaisycabin-app:
    build:
      context: ./containers/app-2
      dockerfile: Dockerfile.dev
    container_name: thedaisycabin-app
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./containers/app-2/src:/app/src
      - ./containers/app-2/public:/app/public
    networks:
      - frontend
    expose:
      - 3000

  ctchan-api:
    build:
      context: ./containers/api
      dockerfile: Dockerfile.dev
    container_name: ctchan-api
    environment:
      FLASK_ENV: 'development'
    volumes:
      - ./containers/api/src:/srv/src
    networks:
      - backend
    expose:
      - 8080

  ctchan-db:
    image: mongo:latest
    container_name: ctchan-db
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE}'
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    volumes:
      - ./containers/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./containers/db/mongo-volume:/data/db
    networks:
      - backend
    restart: unless-stopped
    command: mongod --auth


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodb:
    driver: local
