## Stage 1: Build react app
FROM node:10.13-alpine as build-app
WORKDIR /app
# Install dependencies
COPY ./app/package.json ./app/yarn.lock ./
RUN yarn
# Add the project
COPY ./app/ ./
# Production build
RUN yarn build

## Stage 2: production environment
FROM nginx:1.16.0-alpine
COPY --from=build-app ./app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.prod.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
